### ISSUE TITLE
PHP Fatal error:  Class 'DBConnect' not found in ~/includes/scripts/collect-nest-data.php on line 12

### ISSUE THREAD

**Issue by Garywoo** [f0rkz/Bootstrap-Nest-Administration-Tool#28]
Running a Debian server with PHP 5.6.30, but am running into the same issue as [this user on Reddit](https://www.reddit.com/r/Nest/comments/2odolw/progress_to_the_bootstrap_nest_web_admin/cre9e2q/). I've manually run the *collect-nest-data.php* and got the same error about the class `DBConnect` not being found. I can see the class being declared in *dbconnect.php*.

I've tried changing the `include()`s in *collect-nest-data.php* to `require_once()`s which has had the effect of stopping the error from appearing when manually running the script, however I'm not seeing any data in my graphs in the UI, and I'm not sure where else to check for further errors.

**Comment by f0rkz** [comment]
Wew lad this project is pretty old. Good news is I got it working and encountered the same problems. What directory are you in when you run the php script? You need to be in the _same_ directory as the php script (because of the janky way past-me did includes and php). Give that a try and see if it works.

**Comment by Garywoo** [comment]
Awesome! This worked. Thanks.
After I did this I got some understandable errors, and realised my credentials were wrong. Updated them and the cron job is working correctly now 👍
